ZBenz/ZBeans-Revised/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ZBeansApplication.Models;
using ZBeansApplication.Data;
using Microsoft.Extensions.Logging;

namespace ZBeansApplication.Controllers
{
    public class EmployeeController : Controller
    {
        private ILogger _logger;

        public EmployeeController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Profile()
        {
            return View();
        }

        public IActionResult Schedule()
        {
            return View(new WeekScheduleModel());
        }


    }
}

ZBenz/ZBeans-Revised/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;


using ZBeansApplication.Data;
using ZBeansApplication.Models;

namespace ZBeansApplication.Controllers
{
    public class LoginController : Controller
    {
        private ILogger _logger;


        public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;

        }

        public IActionResult Index()
        {
            ViewData["ZBeansLogo"] = "/images/SMALL_1500x.png";
            return View();
        }

        // TODO: 
        // This method tells the backend to pull the password from the server, check it against the
        // submitted password, redirect to certain pages based on that info.
        public IActionResult Submit()
        {
            _logger.LogInformation("Username: ");




            return View();
        }
    }
}

ZBenz/ZBeans-Revised/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;

using System.Threading.Tasks;
using System.Threading;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ZBeansApplication.Models;
using ZBeansApplication.Data;

namespace ZBeansApplication.Controllers
{
    public class ManagerController : Controller
    {
        private ILogger _logger;

        public ManagerController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Location Select";
            return View();
        }

        public IActionResult Schedule()
        {

            return View(new WeekScheduleModel());
        }

        public IActionResult Employees()
        {
            return View();
        }

        public IActionResult CreateEmployee()
        {
            return View();
        }

        public async Task<IActionResult> StoreEmployeeData(User user)
        {
            return RedirectToAction("Employees");
        }

    }
}

ZBenz/ZBeans-Revised/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZBeans_Revised</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ZBeans_Revised</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ZBeans_Revised - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ZBenz/ZBeans-Revised/Views/Shared/_LayoutEmployee.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Employee</title>

    <!-- Link stylesheet for this application-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet" />


</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- STARTING NEW-->
        <!-- Sidebar -->
  
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Employee" asp-action="Index">
                <div class="sidebar-brand-text mx-3">Z Beans</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Home -->
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Employee" asp-action="Index">
                    <i class="fas fa-home"></i>
                    <span>Home</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">


            <!-- Nav Item - Profile -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Employee" asp-action="Profile">
                    <i class="fas fa-user-circle"></i>
                    <span>Profile</span>
                </a>
            </li>

            <!-- Nav Item - Schedule -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Employee" asp-action="Schedule">
                    <i class="fas fa-calendar-alt"></i>
                    <span>Schedule</span>
                </a>
            </li>
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>

        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            @RenderBody()
        </div>
 
            <!-- Bootstrap core JavaScript-->
            <script src="~/vendor/jquery/jquery.min.js"></script>
            <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

            <!-- Core plugin JavaScript-->
            <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

            <!-- Custom scripts for all pages-->
            <script src="~/js/sb-admin-2.min.js"></script>

            <!-- Page level plugins -->
            <script src="~/vendor/chart.js/Chart.min.js"></script>

            <!-- Page level custom scripts -->
            <script src="~/js/demo/chart-area-demo.js"></script>
            <script src="~/js/demo/chart-pie-demo.js"></script>


</body>

</html>

ZBenz/ZBeans-Revised/Views/Shared/_LayoutManager.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Manager POV";
}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"]</title>

    <!-- Link stylesheet for this application-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet" />
    <link href="~/fontawesome-free/css/all.min.css" rel="stylesheet" />

</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- STARTING NEW-->
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Login" asp-action="Index">
                <div class="sidebar-brand-text mx-3">Z Beans</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Manager" asp-action="Index">
                    <i class="fas fa-store"></i>
                    <span>Store Select</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">


            <!-- Nav Item - Employees -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Manager" asp-action="Employees">
                    <i class="fas fa-user-circle"></i>
                    <span>Employees</span>
                </a>
            </li>

            <!-- Nav Item - Schedule -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Manager" asp-action="Schedule">
                    <i class="fas fa-calendar-alt"></i>
                    <span>Schedule</span>
                </a>
            </li>
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            @RenderBody()
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-pie-demo.js"></script>


</body>

</html>